host: https://new-api-events-16041.herokuapp.com/
info:
  contact:
    email: support@swagger.io
    name: API-Event Support
    url: http://www.swagger.io/support
  description: Documentação da API de eventos.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API-Event
  version: "1.0"
paths: {}
swagger: "2.0"
